version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
    ports:
      - "8000:8000"  # Expose the app to port 8000 on localhost
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - laravel
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:DbUv2OorihPt+0iRjvZz5x5Bi8Gv0icMw5+2+9mA/HI=
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC
      - APP_URL=http://localhost
      - APP_LOCALE=en
      - APP_FALLBACK_LOCALE=en
      - APP_FAKER_LOCALE=en_US
      - APP_MAINTENANCE_DRIVER=file
      # APP_MAINTENANCE_STORE=database
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=life
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - CACHE_STORE=database
      - CACHE_PREFIX=
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - MAIL_MAILER=log
      - MAIL_SCHEME=null
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME="${APP_NAME}"
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - VITE_APP_NAME="${APP_NAME}"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: life
    ports:
      - "3306:3306"
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage for MySQL data

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - laravel
    ports:
      - "6379:6379"

volumes:
  mysql_data:  # Define volume for MySQL persistent storage

networks:
  laravel:
    driver: bridge
